ITLabWeb/Controllers/ColumnController.cs
using ITLab.Classes.Database;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ITLabWeb.Controllers
{
    public class ColumnController : Controller
    {
        DatabaseManager inst = DatabaseManager.Instance;
        // GET: ColumnController/Create
        public ActionResult Create(string tabName)
        {
            ViewBag.tabName = tabName;
            return View();
        }

        // POST: ColumnController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string name, string type, string tabName)
        {
            try
            {
                inst.AddColumn(tabName, name, type);
                return RedirectToAction(nameof(Index), "Table", new {name = tabName});
            }
            catch
            {
                return View();
            }
        }

        public ActionResult CreateSet(string tabName)
        {
            ViewBag.tabName = tabName;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateSet(string name, string values, string tabName)
        {
            try
            {
                inst.AddSetColumn(tabName, name, values);
                return RedirectToAction(nameof(Index), "Table", new { name = tabName });
            }
            catch
            {
                return View();
            }
        }


        // GET: ColumnController/Delete/5
        public ActionResult Delete(string tabName, string name)
        {
            ViewBag.tabName = tabName;
            ViewBag.name = name;
            return View();
        }

        // POST: ColumnController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string tabName, string name) {
            inst.DeleteColumn(tabName, inst.Database.GetTable(tabName).Columns.FindIndex(x => x.Name == name));
            return RedirectToAction(nameof(Index), "Table", new { name = tabName });
        }
    }
}

ITLabWeb/Controllers/RowController.cs
using ITLab.Classes.Database;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.InteropServices;

namespace ITLabWeb.Controllers
{
    public class RowController : Controller
    {
        DatabaseManager inst = DatabaseManager.Instance;


        // GET: RowController/Create
        public ActionResult Create(string tabName)
        {
            ViewBag.tabName = tabName;
            return View();
        }

        // POST: RowController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string tabName, string values)
        {
            try
            {
                inst.AddRow(tabName, values);
                return RedirectToAction(nameof(Index), "Table", new { name = tabName});
            }
            catch
            {
                return View();
            }
        }

        // GET: RowController/Edit/5
        public ActionResult Edit(string tabName, int id)
        {
            ViewBag.tabName = tabName;
            ViewBag.id = id;
            return View();
        }

        // POST: RowController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string tabName, int rowId, string values)
        {
            try
            {
                inst.EditRow(tabName, values, rowId);
                return RedirectToAction(nameof(Index), "Table", new { name = tabName });
            }
            catch
            {
                return View();
            }
        }

        // GET: RowController/Delete/5
        public ActionResult Delete(string tabName, int id)
        {
            ViewBag.tabName = tabName;
            ViewBag.id = id;
            return View();
        }

        // POST: RowController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string tabName, int rowId)
        {
            try
            {
                inst.DeleteRow(tabName, rowId);
                return RedirectToAction(nameof(Index), "Table", new { name = tabName });
            }
            catch
            {
                return View();
            }
        }
    }
}

ITLabWeb/Controllers/TableController.cs
using ITLab.Classes.Database;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ITLabWeb.Controllers
{
    public class TableController : Controller
    {
        DatabaseManager inst = DatabaseManager.Instance;
        // GET: TableController
        public ActionResult Index(string name)
        {
            Table res = inst.Database.GetTable(name);
            if (res == null)
            {
                ViewBag.errMsg = "No Table";
                ViewBag.Table = new Table("");
            }
            else
            {
                ViewBag.errMsg = res.Name;
                ViewBag.Table = res;
            }
            return View();
        }

        public ActionResult MultiplyRes(string name1, string name2)
        {
            Table res = inst.Multiply(name1, name2);
            if (res == null)
            {
                ViewBag.errMsg = "No Table";
                ViewBag.Table = new Table("");
            }
            else
            {
                ViewBag.errMsg = res.Name;
                ViewBag.Table = res;
            }
            return View();
        }

        public ActionResult Multiply()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Multiply(string name1, string name2)
        {
            try
            {
                Table res = inst.Multiply(name1, name2);
                return RedirectToAction(nameof(MultiplyRes), new { name1=name1, name2=name2 });
            }
            catch
            {
                return View();
            }
        }

        // GET: TableController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TableController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TableController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(string name)
        {
            try
            {
                inst.AddTable(name);
                return RedirectToAction(nameof(Index), "Database");
            }
            catch
            {
                return View();
            }
        }

        // GET: TableController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TableController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(string? name)
        {
            ViewBag.tabName = name;
            return View();
        }

        // POST: TableController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string name)
        {

            inst.DeleteTable(name);
             return RedirectToAction(nameof(Index), "Database");

            
        }
    }
}

ITLabWeb/Views/Table/Create.cshtml
<form method="post" action="~/Table/Create">
    <p>
        <label>Назва</label><br />
        @Html.TextBox("name")
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

ITLabWeb/Views/Table/Delete.cshtml
@using ITLab.Classes.Database
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Table";
}
 
<form method="post" action="~/Table/Delete">
    <p>
        <h3>You sure you want to delete @ViewBag.tabName ?</h3>
    <input hidden value="@ViewBag.tabName" name="name" />
    </p>
    <p>
        <input type="submit" value="Відправити" />
    </p>
</form>

ITLabWeb/Views/Table/Index.cshtml
@using ITLab.Classes.Database
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Table";
}

<h3>@ViewBag.errMsg</h3>
<table>
    <tr>
        @foreach (Column col in ViewBag.Table.Columns)
        {
            <th><a class="btn btn-secondary" asp-controller="Column" asp-action="Delete" asp-route-tabName="@ViewBag.Table.Name" asp-route-name="@col.Name"> Видалити </a></th>
        }
    </tr>
    <tr>
    @foreach(Column col in ViewBag.Table.Columns){
        <th>@col.Name</th>
    }
    </tr>
    @{
        int i = 0;
    }
    @foreach(Row row in ViewBag.Table.Rows){
        
        <tr>
           
            @foreach(string val in row.Values){
                <td>@val</td>
            }
            <td><a class="btn btn-primary" asp-controller="Row" asp-action="Edit" asp-route-tabName="@ViewBag.Table.Name" asp-route-id="@i">Редагувати</a><a class="btn btn-primary" asp-controller="Row" asp-action="Delete" asp-route-tabName="@ViewBag.Table.Name" asp-route-id="@i">Видалити</a></td>
        </tr>
        i++;
    }
</table>

<a class = "btn btn-primary" asp-controller="Column" asp-action="Create" asp-route-tabName = "@ViewBag.Table.Name"> Додати колонку </a> 
<a class="btn btn-primary" asp-controller="Column" asp-action="CreateSet" asp-route-tabName="@ViewBag.Table.Name"> Додати колонку множини </a>
<a class="btn btn-primary" asp-controller="Row" asp-action="Create" asp-route-tabName="@ViewBag.Table.Name">Додати рядок</a>

ITLabWeb/Views/Table/Multiply.cshtml
<form method="post" action="~/Table/Multiply">
    <p>
        <label>Таблиця1:</label><br />
        @Html.TextBox("name1")
    </p> <p>
        <label>Таблиці2:</label><br />
        @Html.TextBox("name2")
    </p>
    <p>
        <input type="submit" value="Помножити" />
    </p>
</form>

ITLabWeb/Views/Table/MultiplyRes.cshtml
@using ITLab.Classes.Database
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Table";
}

<h3>@ViewBag.errMsg</h3>
<table>
    <tr>
        @foreach (Column col in ViewBag.Table.Columns)
        {
            <th>@col.Name</th>
        }
    </tr>
    @{
        int i = 0;
    }
    @foreach (Row row in ViewBag.Table.Rows)
    {

        <tr>

            @foreach (string val in row.Values)
            {
                <td>@val</td>
            }
        </tr>
    }
</table>